/**
 * Small, reusable building blocks. Every screen is made from these, so
 * changing a colour or a corner radius here updates the whole app.
 *
 * This is the ONLY component file allowed to set fontSize / lineHeight /
 * fontFamily (via the `type` map in theme/tokens.ts). ESLint enforces it.
 * Spec: docs/mobile/DESIGN_SYSTEM.md ("Grove v2").
 *
 * Surface rules (spec §5), in one breath: content sits on the paper by
 * default; lists use hairlines, not boxes; raised white rows only for
 * things you choose between; one forest panel per screen; tinted blocks
 * only for feedback.
 */
import type { ReactNode } from 'react';
import {
  Image,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  View,
  type StyleProp,
  type TextStyle,
  type ViewStyle,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { domainColor } from '../content/certifications';
import type { DomainInfo } from '../content/types';
import {
  font,
  forestHighlight,
  grainOp,
  maxScale,
  radius,
  raisedShadow,
  space,
  STEM_LONG_CHARS,
  stemLong,
  type,
  type TypeVariant,
} from '../theme/tokens';
import { useTheme } from '../theme/useTheme';
import { Botany, type BotanyKind } from './glyphs';
import { Check, ChevronRight, ICON_STROKE } from './icons';

/** Icon sizes: inline with text, in rows/circles, and in the tab bar/header. */
export const ICON_SIZE = { inline: 16, row: 20, bar: 24 } as const;

/** Tab-bar height above the safe-area inset (spec §6: 56 + safe area). */
export const TAB_BAR_HEIGHT = 56;

// The paper grain tiles (generated by scripts/make-grain.mjs).
const GRAIN = {
  light: require('../../assets/grain-light.png'),
  dark: require('../../assets/grain-dark.png'),
};

// ── Grain: the paper texture over the whole app (spec §10.5) ──────────
// Sits ABOVE content so bars, panels and rows share one texture, but
// never takes touches and is invisible to screen readers.
export function Grain() {
  const { isDark } = useTheme();
  return (
    <View style={[StyleSheet.absoluteFill, styles.noTouch]} accessible={false} importantForAccessibility="no-hide-descendants">
      <Image
        source={isDark ? GRAIN.dark : GRAIN.light}
        resizeMode="repeat"
        style={{ width: '100%', height: '100%', opacity: isDark ? grainOp.dark : grainOp.light }}
      />
    </View>
  );
}

// ── Screen: safe-area aware page with optional scrolling ──────────────
export function Screen({
  children,
  scroll = true,
  edges = ['top'],
}: {
  children: ReactNode;
  scroll?: boolean;
  edges?: ('top' | 'bottom')[];
}) {
  const { c } = useTheme();
  const inner = scroll ? (
    <ScrollView contentContainerStyle={styles.screenPad} keyboardShouldPersistTaps="handled">
      {children}
    </ScrollView>
  ) : (
    <View style={[styles.screenPad, { flex: 1 }]}>{children}</View>
  );
  return <SafeAreaView edges={edges} style={{ flex: 1, backgroundColor: c.bg }}>{inner}</SafeAreaView>;
}

// ── Text: the Grove v2 type scale ──────────────────────────────────────
// Fraunces (serif) for reading moments and big numbers: number, stat,
// display, hero, stem, quote, stage. Figtree (sans) for everything you
// tap or scan: headline, label, body, small, meta, caption, tab.
export type Variant = TypeVariant;

export function T({
  children,
  v = 'body',
  color,
  style,
  center,
  num,
  accessibilityLabel,
  accessibilityRole,
  maxFontSizeMultiplier,
  numberOfLines,
}: {
  children: ReactNode;
  v?: Variant;
  color?: string;
  style?: StyleProp<TextStyle>;
  center?: boolean;
  /** Tabular figures, so numbers (%, timers, "1 of 3") don't jiggle as they change. */
  num?: boolean;
  accessibilityLabel?: string;
  accessibilityRole?: 'header' | 'text';
  /** Override the spec's per-variant cap (theme/tokens.ts `maxScale`). Never 1.0. */
  maxFontSizeMultiplier?: number;
  numberOfLines?: number;
}) {
  const { c } = useTheme();
  // Meta lines and small captions are secondary text by default.
  const defaultColor = v === 'meta' || v === 'caption' ? c.ink2 : c.ink;
  return (
    <Text
      accessibilityLabel={accessibilityLabel}
      accessibilityRole={accessibilityRole}
      maxFontSizeMultiplier={maxFontSizeMultiplier ?? maxScale[v]}
      numberOfLines={numberOfLines}
      style={[type[v], { color: color ?? defaultColor }, num && styles.num, center && { textAlign: 'center' }, style]}
    >
      {children}
    </Text>
  );
}

/** A question stem: Fraunces 21/30, stepping down to 20/29 for long stems. */
export function Stem({ children, color }: { children: string; color?: string }) {
  return (
    <T v="stem" color={color} style={children.length > STEM_LONG_CHARS ? stemLong : undefined}>
      {children}
    </T>
  );
}

// ── Buttons ───────────────────────────────────────────────────────────
export type ButtonKind = 'primary' | 'secondary' | 'ghost' | 'danger' | 'forest';

export function Button({
  label,
  onPress,
  kind = 'primary',
  disabled,
  style,
  icon,
  iconLeading,
  accessibilityHint,
  accessibilityLabel,
}: {
  label: string;
  onPress: () => void;
  kind?: ButtonKind;
  disabled?: boolean;
  style?: StyleProp<ViewStyle>;
  /** Optional icon, drawn in the label colour: trailing (primary) or leading (forest). */
  icon?: (color: string) => ReactNode;
  iconLeading?: boolean;
  accessibilityHint?: string;
  /** Spoken name when the visible label is a symbol (e.g. "‹"). */
  accessibilityLabel?: string;
}) {
  const { c } = useTheme();
  // Each kind = fill · border · label colour (spec §6 "Button").
  // Disabled is its own look (soft + muted), not a faded copy.
  const look = disabled
    ? { bg: c.soft, border: c.soft, fg: c.muted }
    : {
        primary: { bg: c.btn, border: c.btn, fg: c.onBtn },
        secondary: { bg: 'transparent', border: c.control, fg: c.ink },
        ghost: { bg: 'transparent', border: 'transparent', fg: c.accentText },
        danger: { bg: c.wrongBg, border: c.wrongBg, fg: c.wrong },
        forest: { bg: c.pill, border: c.pill, fg: c.onPill },
      }[kind];
  const isForest = kind === 'forest';
  const isGhost = kind === 'ghost';
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ disabled }}
      accessibilityHint={accessibilityHint}
      accessibilityLabel={accessibilityLabel ?? label}
      onPress={onPress}
      disabled={disabled}
      style={({ pressed }) => [
        isForest ? styles.buttonForest : isGhost ? styles.buttonGhost : styles.button,
        { backgroundColor: look.bg, borderColor: look.border },
        // Pressed = a tiny squeeze, not a colour change.
        pressed && { transform: [{ scale: 0.98 }], opacity: 0.92 },
        style,
      ]}
    >
      {iconLeading && icon?.(look.fg)}
      <Text maxFontSizeMultiplier={1.6} style={[isForest || isGhost ? type.label : styles.buttonLabel, { color: look.fg }]}>
        {label}
      </Text>
      {!iconLeading && icon?.(look.fg)}
    </Pressable>
  );
}

// ── Card: a surface ───────────────────────────────────────────────────
// raised = white row with a soft shadow (dark: 1.5px outline) for things you
// choose between; plain = no box at all; forest = the one brand panel.
export function Card({
  children,
  style,
  onPress,
  emphasis,
  variant = 'raised',
  accessibilityLabel,
}: {
  children: ReactNode;
  style?: StyleProp<ViewStyle>;
  onPress?: () => void;
  /** A 1.5px brand-green outline: "this matters most right now". */
  emphasis?: boolean;
  variant?: 'raised' | 'plain' | 'forest';
  accessibilityLabel?: string;
}) {
  const { c, isDark } = useTheme();
  const look =
    variant === 'forest'
      ? [styles.forest, { backgroundColor: c.forest }, isDark && styles.forestLift]
      : variant === 'plain'
        ? null
        : [
            styles.card,
            { backgroundColor: c.raised, borderColor: emphasis ? c.accent : isDark ? c.line : 'transparent' },
            !isDark && raisedShadow,
          ];
  const base = [look, style];
  if (!onPress) return <View style={base}>{children}</View>;
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel}
      onPress={onPress}
      style={({ pressed }) => [base, pressed && { transform: [{ scale: 0.98 }] }]}
    >
      {children}
    </Pressable>
  );
}

// ── HeroPanel: the forest panel with botanical line art (spec §6) ─────
export function HeroPanel({
  caption,
  captionExtra,
  title,
  meta,
  action,
  art = 'frond',
  style,
}: {
  caption?: string;
  /** Anything after the caption on the same line (e.g. plan leaf marks). */
  captionExtra?: ReactNode;
  title: string;
  meta?: string;
  action?: { label: string; onPress: () => void; icon?: (color: string) => ReactNode; hint?: string };
  art?: BotanyKind;
  style?: StyleProp<ViewStyle>;
}) {
  const { c } = useTheme();
  return (
    <Card variant="forest" style={style}>
      {/* Decorative art bleeds off the top-right; screen readers skip it. */}
      <View style={styles.heroArt} accessible={false} importantForAccessibility="no-hide-descendants">
        <Botany kind={art} color={c.forestLine} />
      </View>
      {caption && (
        <Row gap={space.sm + 2}>
          <T v="caption" color={c.onForest2}>{caption}</T>
          {captionExtra}
        </Row>
      )}
      {/* While the title fits in 2 lines it stays clear of the art (maxWidth 250). */}
      <T v="hero" color={c.onForest} accessibilityRole="header" style={{ marginTop: caption ? space.sm : 0, maxWidth: title.length <= 34 ? 250 : undefined }}>
        {title}
      </T>
      {meta && <T v="meta" color={c.onForest2} style={{ marginTop: 6 }}>{meta}</T>}
      {action && (
        <Button
          kind="forest"
          label={action.label}
          onPress={action.onPress}
          accessibilityHint={action.hint}
          icon={action.icon}
          iconLeading
          style={{ marginTop: 18, alignSelf: 'flex-start' }}
        />
      )}
    </Card>
  );
}

// ── Section: headline + optional meta on the right ────────────────────
export function Section({ title, meta, style }: { title: string; meta?: string; style?: StyleProp<ViewStyle> }) {
  return (
    <View style={[styles.section, style]}>
      <T v="headline" accessibilityRole="header" style={{ flexShrink: 1 }}>{title}</T>
      {meta && <T v="meta">{meta}</T>}
    </View>
  );
}

// ── IconCircle: 40pt soft circle holding a row-size icon ──────────────
export function IconCircle({ children }: { children: ReactNode }) {
  const { c } = useTheme();
  return <View style={[styles.iconCircle, { backgroundColor: c.soft }]}>{children}</View>;
}
/** Old name, kept so unredesigned screens still compile. */
export const IconTile = IconCircle;

// ── ListRow: icon circle · title/subtitle · trailing · chevron, hairline below
export function ListRow({
  icon,
  title,
  subtitle,
  trailing,
  onPress,
  last,
  chevron = true,
  accessibilityLabel,
  accessibilityHint,
}: {
  icon?: ReactNode;
  title: string;
  subtitle?: string;
  trailing?: ReactNode;
  onPress?: () => void;
  /** The last row in a list has no hairline. */
  last?: boolean;
  chevron?: boolean;
  accessibilityLabel?: string;
  accessibilityHint?: string;
}) {
  const { c } = useTheme();
  const body = (
    <>
      {icon && <IconCircle>{icon}</IconCircle>}
      <View style={{ flex: 1, minWidth: 0 }}>
        <T v="label">{title}</T>
        {subtitle && <T v="meta">{subtitle}</T>}
      </View>
      {trailing}
      {onPress && chevron && <ChevronRight size={18} color={c.muted} strokeWidth={ICON_STROKE} />}
      {/* Hairline inset to where the text starts. */}
      {!last && <View style={[styles.hairline, { left: icon ? 54 : 0, backgroundColor: c.line }]} />}
    </>
  );
  if (!onPress) return <View style={styles.listRow}>{body}</View>;
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel ?? (subtitle ? `${title}, ${subtitle}` : title)}
      accessibilityHint={accessibilityHint}
      onPress={onPress}
      style={({ pressed }) => [styles.listRow, pressed && { backgroundColor: c.soft }]}
    >
      {body}
    </Pressable>
  );
}

// ── ProgressBar: 0..1 ─────────────────────────────────────────────────
export function ProgressBar({ value, color, height = 8 }: { value: number; color?: string; height?: number }) {
  const { c } = useTheme();
  const pct = Math.max(0, Math.min(1, value)) * 100;
  const r = Math.min(height, radius.sm);
  return (
    <View
      accessibilityRole="progressbar"
      accessibilityValue={{ min: 0, max: 100, now: Math.round(pct) }}
      style={{ height, borderRadius: r, backgroundColor: c.track, overflow: 'hidden' }}
    >
      <View style={{ width: `${pct}%`, height, backgroundColor: color ?? c.accent, borderRadius: r }} />
    </View>
  );
}

// ── SegmentBar: quiz progress, one segment per question (spec §6) ─────
// Done = accent, current = ink2, rest = track. Over 20 questions it turns
// into one continuous bar so segments never get too thin to see.
export function SegmentBar({ total, done, current }: { total: number; done: number; current: number }) {
  const { c } = useTheme();
  const a11y = {
    accessibilityRole: 'progressbar' as const,
    accessibilityLabel: `Question ${current + 1} of ${total}`,
    accessibilityValue: { min: 0, max: total, now: done },
  };
  if (total > 20) {
    return (
      <View {...a11y} style={[styles.segTrack, { backgroundColor: c.track }]}>
        <View style={{ width: `${(done / total) * 100}%`, height: 4, backgroundColor: c.accent }} />
      </View>
    );
  }
  return (
    <View {...a11y} style={styles.segRow}>
      {Array.from({ length: total }, (_, i) => (
        <View
          key={i}
          style={[styles.seg, { backgroundColor: i < done ? c.accent : i === current ? c.ink2 : c.track }]}
        />
      ))}
    </View>
  );
}

// ── Domain dot: a small swatch in the domain's tone ───────────────────
// Domains 6+ (e.g. CISSP) reuse the 5 tones, drawn hollow so they stay distinct.
export function DomainDot({ domain }: { domain: DomainInfo }) {
  const { isDark } = useTheme();
  const color = domainColor(domain.tone, isDark);
  const hollow = Number(domain.id) > 5;
  return <View style={[styles.dot, hollow ? { borderWidth: 2, borderColor: color } : { backgroundColor: color }]} />;
}

// ── Tag: non-interactive label, no fill ("● IS Audit · Analysis") ─────
export function Tag({ label, domain, color }: { label: string; domain?: DomainInfo; color?: string }) {
  return (
    <View style={styles.tag}>
      {domain && <DomainDot domain={domain} />}
      <T v="meta" color={color} style={{ flexShrink: 1 }}>{label}</T>
    </View>
  );
}

// ── Pill: small, non-interactive label on a soft fill ────────────────
// Sentence case. `domain` shows the domain's colour as a dot next to
// readable text, because domain tones are never used AS text.
export function Pill({
  label,
  color,
  bg,
  domain,
  accessibilityLabel,
}: {
  label: string;
  color?: string;
  bg?: string;
  domain?: DomainInfo;
  accessibilityLabel?: string;
}) {
  const { c } = useTheme();
  return (
    <View style={[styles.pill, { backgroundColor: bg ?? c.soft }]}>
      {domain && <DomainDot domain={domain} />}
      <T v="meta" accessibilityLabel={accessibilityLabel} color={color ?? c.ink2}>{label}</T>
    </View>
  );
}

// ── Chip: selectable filter (spec §6) ─────────────────────────────────
// Selected = ink fill + bg label + leading ✓ (shape AND colour, never green).
export function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) {
  const { c } = useTheme();
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ selected }}
      accessibilityLabel={label} // the ✓ is visual; "selected" state is spoken
      onPress={onPress}
      hitSlop={4} // 40pt chip + 4pt each side = 48pt touch target
      style={({ pressed }) => [
        styles.chip,
        {
          borderColor: selected ? c.ink : c.control,
          backgroundColor: selected ? c.ink : pressed ? c.soft : 'transparent',
        },
      ]}
    >
      {selected && <Check size={14} color={c.bg} strokeWidth={2.5} />}
      <Text maxFontSizeMultiplier={2} style={[styles.chipLabel, { color: selected ? c.bg : c.ink }]}>{label}</Text>
    </Pressable>
  );
}

// ── Toggle: an on/off switch in our colours ──────────────────────────
// Wraps the platform Switch so its thumb never falls back to a stock
// teal/blue. On the web build the "on" thumb needs `activeThumbColor`.
export function Toggle({
  value,
  onValueChange,
  disabled,
  accessibilityLabel,
}: {
  value: boolean;
  onValueChange: (v: boolean) => void;
  disabled?: boolean;
  accessibilityLabel: string;
}) {
  const { c } = useTheme();
  const webOnly = Platform.OS === 'web' ? ({ activeThumbColor: c.onBtn } as object) : {};
  return (
    <Switch
      accessibilityLabel={accessibilityLabel}
      value={value}
      disabled={disabled}
      onValueChange={onValueChange}
      thumbColor={c.onBtn}
      trackColor={{ true: c.btn, false: c.muted }}
      ios_backgroundColor={c.muted}
      {...webOnly}
    />
  );
}

// ── Stat tile: no box. Serif number + meta label, stacked ─────────────
export function Stat({ value, label, color }: { value: string; label: string; color?: string }) {
  return (
    <View style={{ flex: 1 }}>
      <T v="stat" color={color}>{value}</T>
      <T v="meta" style={{ marginTop: space.xs }}>{label}</T>
    </View>
  );
}

// ── Tab bar label: "Today", with a 4pt dot under the active tab ───────
// The dot means the active tab isn't shown by colour alone (spec §6).
export function TabLabel({ label, focused }: { label: string; focused: boolean }) {
  const { c } = useTheme();
  return (
    <View style={styles.tabLabel} accessibilityShowsLargeContentViewer accessibilityLargeContentTitle={label}>
      <T v="tab" color={focused ? c.ink : c.muted}>{label}</T>
      <View style={[styles.tabDot, { backgroundColor: focused ? c.accent : 'transparent' }]} />
    </View>
  );
}

export function Row({ children, gap = space.md, style }: { children: ReactNode; gap?: number; style?: StyleProp<ViewStyle> }) {
  return <View style={[{ flexDirection: 'row', alignItems: 'center', gap }, style]}>{children}</View>;
}

export function Gap({ h = space.lg }: { h?: number }) {
  return <View style={{ height: h }} />;
}

const styles = StyleSheet.create({
  screenPad: { paddingHorizontal: space.gutter, paddingTop: space.lg, paddingBottom: space.xxxl * 2 },
  num: { fontVariant: ['tabular-nums'] },
  noTouch: { pointerEvents: 'none' },
  button: {
    minHeight: 56, // spec: 56 tall, a comfortable thumb target (WCAG 2.5.8)
    borderRadius: radius.pill,
    borderWidth: 1.5,
    paddingHorizontal: space.xl,
    flexDirection: 'row',
    gap: space.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonForest: {
    minHeight: 48,
    borderRadius: radius.pill,
    borderWidth: 0,
    paddingHorizontal: 22,
    flexDirection: 'row',
    gap: space.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonGhost: {
    minHeight: 44,
    borderWidth: 0,
    paddingHorizontal: space.sm,
    flexDirection: 'row',
    gap: space.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonLabel: { fontFamily: font.sans600, fontSize: 17, lineHeight: 22 },
  card: { borderRadius: radius.md, borderWidth: 1.5, padding: space.lg },
  forest: { borderRadius: radius.lg, padding: 22, overflow: 'hidden' },
  // Dark mode: 1px inner top highlight so the panel separates from `bg`.
  forestLift: { borderTopWidth: 1, borderTopColor: forestHighlight },
  heroArt: { position: 'absolute', right: -18, top: -14 },
  section: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: space.md,
    marginTop: 30,
    marginBottom: 2,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listRow: { flexDirection: 'row', alignItems: 'center', gap: 14, minHeight: 64, paddingVertical: 13 },
  hairline: { position: 'absolute', right: 0, bottom: 0, height: 1 },
  segRow: { flex: 1, flexDirection: 'row', gap: 3 },
  seg: { flex: 1, height: 4, borderRadius: 2 },
  segTrack: { flex: 1, height: 4, borderRadius: 2, overflow: 'hidden' },
  dot: { width: 8, height: 8, borderRadius: radius.pill },
  tag: { flexDirection: 'row', alignItems: 'center', gap: space.sm },
  pill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: radius.pill,
    paddingHorizontal: space.md,
    minHeight: 32,
  },
  chip: {
    minHeight: 40,
    borderRadius: radius.pill,
    borderWidth: 1.5,
    paddingHorizontal: space.lg,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipLabel: { fontFamily: font.sans600, fontSize: 15, lineHeight: 20 },
  tabLabel: { alignItems: 'center', gap: 1 },
  tabDot: { width: 4, height: 4, borderRadius: 2 },
});
