/**
 * Small, reusable building blocks. Every screen is made from these, so
 * changing a colour or a corner radius here updates the whole app.
 *
 * This is the ONLY component file allowed to set fontSize / lineHeight /
 * fontFamily (via the `type` map in theme/tokens.ts). ESLint enforces it.
 * Spec: docs/mobile/DESIGN_SYSTEM.md ("Grove v2").
 *
 * Surface rules (spec §5), in one breath: content sits on the paper by
 * default; lists use hairlines, not boxes; raised white rows only for
 * things you choose between; one forest panel per screen; tinted blocks
 * only for feedback.
 */
import { useEffect, type ReactNode } from 'react';
import {
  Image,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  useWindowDimensions,
  View,
  type StyleProp,
  type TextStyle,
  type ViewStyle,
} from 'react-native';
import Animated, { Easing, ReduceMotion, useAnimatedStyle, useSharedValue, withDelay, withTiming } from 'react-native-reanimated';
import { SafeAreaView } from 'react-native-safe-area-context';
import Svg, { Defs, LinearGradient, Rect, Stop } from 'react-native-svg';
import { domainColor } from '../content/certifications';
import type { DomainInfo } from '../content/types';
import { lastWholeWordIndex } from '../engine/games/priorityLens';
import {
  font,
  forestHighlight,
  grainOp,
  LARGE_TEXT,
  maxScale,
  numeralUnit,
  percentSup,
  radius,
  raisedShadow,
  serifNumeral,
  space,
  STEM_LONG_CHARS,
  stemLong,
  type,
  type NumeralSize,
  type TypeVariant,
} from '../theme/tokens';
import { useTheme } from '../theme/useTheme';
import { Botany, Seedling, type BotanyKind } from './glyphs';
import { Check, ChevronLeft, ChevronRight, ICON_STROKE, X } from './icons';

/** Icon sizes: inline with text, in rows/circles, and in the tab bar/header. */
export const ICON_SIZE = { inline: 16, row: 20, bar: 24 } as const;

/** Tab-bar height above the safe-area inset (spec §6: 56 + safe area). */
export const TAB_BAR_HEIGHT = 56;

// The paper grain tiles (generated by scripts/make-grain.mjs).
const GRAIN = {
  light: require('../../assets/grain-light.png'),
  dark: require('../../assets/grain-dark.png'),
};

// ── Grain: the paper texture over the whole app (spec §10.5) ──────────
// Sits ABOVE content so bars, panels and rows share one texture, but
// never takes touches and is invisible to screen readers.
export function Grain() {
  const { isDark } = useTheme();
  return (
    <View style={[StyleSheet.absoluteFill, styles.noTouch]} accessible={false} importantForAccessibility="no-hide-descendants">
      <Image
        source={isDark ? GRAIN.dark : GRAIN.light}
        resizeMode="repeat"
        style={{ width: '100%', height: '100%', opacity: isDark ? grainOp.dark : grainOp.light }}
      />
    </View>
  );
}

// ── Screen: safe-area aware page with optional scrolling ──────────────
export function Screen({
  children,
  scroll = true,
  edges = ['top'],
}: {
  children: ReactNode;
  scroll?: boolean;
  edges?: ('top' | 'bottom')[];
}) {
  const { c } = useTheme();
  const inner = scroll ? (
    <ScrollView contentContainerStyle={styles.screenPad} keyboardShouldPersistTaps="handled">
      {children}
    </ScrollView>
  ) : (
    <View style={[styles.screenPad, { flex: 1 }]}>{children}</View>
  );
  return <SafeAreaView edges={edges} style={{ flex: 1, backgroundColor: c.bg }}>{inner}</SafeAreaView>;
}

// ── Text: the Grove v2 type scale ──────────────────────────────────────
// Fraunces (serif) for reading moments and big numbers: number, stat,
// display, hero, stem, quote, stage. Figtree (sans) for everything you
// tap or scan: headline, label, body, small, meta, caption, tab.
export type Variant = TypeVariant;

export function T({
  children,
  v = 'body',
  color,
  style,
  center,
  num,
  accessibilityLabel,
  accessibilityRole,
  maxFontSizeMultiplier,
  numberOfLines,
}: {
  children: ReactNode;
  v?: Variant;
  color?: string;
  style?: StyleProp<TextStyle>;
  center?: boolean;
  /** Tabular figures, so numbers (%, timers, "1 of 3") don't jiggle as they change. */
  num?: boolean;
  accessibilityLabel?: string;
  accessibilityRole?: 'header' | 'text';
  /** Override the spec's per-variant cap (theme/tokens.ts `maxScale`). Never 1.0, except text inside a
   *  fixed-size image (the share card), whose wrapper's accessibilityLabel speaks the full text. */
  maxFontSizeMultiplier?: number;
  numberOfLines?: number;
}) {
  const { c } = useTheme();
  // Meta lines and small captions are secondary text by default.
  const defaultColor = v === 'meta' || v === 'caption' ? c.ink2 : c.ink;
  return (
    <Text
      accessibilityLabel={accessibilityLabel}
      accessibilityRole={accessibilityRole}
      maxFontSizeMultiplier={maxFontSizeMultiplier ?? maxScale[v]}
      numberOfLines={numberOfLines}
      style={[type[v], { color: color ?? defaultColor }, num && styles.num, center && { textAlign: 'center' }, style]}
    >
      {children}
    </Text>
  );
}

/** A question stem: Fraunces 21/30, stepping down to 20/29 for long stems. */
export function Stem({ children, color, highlight }: { children: string; color?: string; highlight?: string | null }) {
  const { c } = useTheme();
  const style = children.length > STEM_LONG_CHARS ? stemLong : undefined;
  // Coach me: mark the LAST capitalised priority word, matched as a whole
  // word (so "MOST" never lights up inside "ALMOST"). Tip colour plus a
  // heavier weight: the weight change is the non-colour cue, and the hint
  // text below also names the word. No underline or background, so it never
  // looks like a link or like an answered (tinted) state.
  const at = highlight ? lastWholeWordIndex(children, highlight) : -1;
  if (!highlight || at < 0) {
    return (
      <T v="stem" color={color} style={style}>
        {children}
      </T>
    );
  }
  return (
    <T v="stem" color={color} style={style}>
      {children.slice(0, at)}
      <Text style={{ color: c.tip, fontFamily: font.serif500 }}>{highlight}</Text>
      {children.slice(at + highlight.length)}
    </T>
  );
}

// ── Buttons ───────────────────────────────────────────────────────────
export type ButtonKind = 'primary' | 'secondary' | 'ghost' | 'danger' | 'forest';

export function Button({
  label,
  onPress,
  kind = 'primary',
  disabled,
  style,
  icon,
  iconLeading,
  accessibilityHint,
  accessibilityLabel,
  selected,
}: {
  label: string;
  onPress: () => void;
  kind?: ButtonKind;
  disabled?: boolean;
  style?: StyleProp<ViewStyle>;
  /** Optional icon, drawn in the label colour: trailing (primary) or leading (forest). */
  icon?: (color: string) => ReactNode;
  iconLeading?: boolean;
  accessibilityHint?: string;
  /** Spoken name when the visible label is a symbol (e.g. "‹"). */
  accessibilityLabel?: string;
  /** For toggle buttons (e.g. Flag): announced as "selected" when on. */
  selected?: boolean;
}) {
  const { c } = useTheme();
  // Each kind = fill · border · label colour (spec §6 "Button").
  // Disabled is its own look (soft + muted), not a faded copy.
  const look = disabled
    ? { bg: c.soft, border: c.soft, fg: c.muted }
    : {
        primary: { bg: c.btn, border: c.btn, fg: c.onBtn },
        secondary: { bg: 'transparent', border: c.control, fg: c.ink },
        ghost: { bg: 'transparent', border: 'transparent', fg: c.accentText },
        danger: { bg: c.wrongBg, border: c.wrongBg, fg: c.wrong },
        forest: { bg: c.pill, border: c.pill, fg: c.onPill },
      }[kind];
  const isForest = kind === 'forest';
  const isGhost = kind === 'ghost';
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ disabled, selected }}
      accessibilityHint={accessibilityHint}
      accessibilityLabel={accessibilityLabel ?? label}
      onPress={onPress}
      disabled={disabled}
      style={({ pressed }) => [
        isForest ? styles.buttonForest : isGhost ? styles.buttonGhost : styles.button,
        { backgroundColor: look.bg, borderColor: look.border },
        // Pressed = a tiny squeeze, not a colour change.
        pressed && { transform: [{ scale: 0.98 }], opacity: 0.92 },
        style,
      ]}
    >
      {iconLeading && icon?.(look.fg)}
      <Text maxFontSizeMultiplier={maxScale.label} style={[isForest || isGhost ? type.label : styles.buttonLabel, { color: look.fg, flexShrink: 1, textAlign: 'center' }]}>
        {label}
      </Text>
      {!iconLeading && icon?.(look.fg)}
    </Pressable>
  );
}

// ── Card: a surface ───────────────────────────────────────────────────
// raised = white row with a soft shadow (dark: 1.5px outline) for things you
// choose between; plain = no box at all; forest = the one brand panel.
export function Card({
  children,
  style,
  onPress,
  emphasis,
  variant = 'raised',
  accessibilityLabel,
}: {
  children: ReactNode;
  style?: StyleProp<ViewStyle>;
  onPress?: () => void;
  /** A 1.5px brand-green outline: "this matters most right now". */
  emphasis?: boolean;
  variant?: 'raised' | 'plain' | 'forest';
  accessibilityLabel?: string;
}) {
  const { c, isDark } = useTheme();
  const look =
    variant === 'forest'
      ? [styles.forest, { backgroundColor: c.forest }, isDark && styles.forestLift]
      : variant === 'plain'
        ? null
        : [
            styles.card,
            { backgroundColor: c.raised, borderColor: emphasis ? c.accent : isDark ? c.line : 'transparent' },
            !isDark && raisedShadow,
          ];
  const base = [look, style];
  if (!onPress) return <View style={base}>{children}</View>;
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel}
      onPress={onPress}
      style={({ pressed }) => [base, pressed && { transform: [{ scale: 0.98 }] }]}
    >
      {children}
    </Pressable>
  );
}

// ── HeroPanel: the forest panel with botanical line art (spec §6) ─────
export function HeroPanel({
  caption,
  captionLead,
  captionExtra,
  title,
  meta,
  action,
  art = 'frond',
  sway = true,
  children,
  style,
  titleLabel,
  wideTitle,
}: {
  caption?: string;
  /** Before the caption on the same line (e.g. a domain dot). */
  captionLead?: ReactNode;
  /** After the caption on the same line (e.g. plan leaf marks). */
  captionExtra?: ReactNode;
  title: string;
  meta?: string;
  action?: { label: string; onPress: () => void; icon?: (color: string) => ReactNode; hint?: string };
  art?: BotanyKind;
  /** Gentle frond sway while the screen is focused (off under Reduce Motion). */
  sway?: boolean;
  /** Extra content under the title (e.g. the clearing card's stats). */
  children?: ReactNode;
  style?: StyleProp<ViewStyle>;
  /** Spoken title, when it differs from the visible one. */
  titleLabel?: string;
  /** Let a short title use the full width (art there is low and sparse). */
  wideTitle?: boolean;
}) {
  const { c } = useTheme();
  const large = useFontScale() >= LARGE_TEXT;
  return (
    <Card variant="forest" style={style}>
      {/* Decorative art bleeds off the top-right; screen readers skip it. */}
      <View style={[styles.heroArt, styles.noTouch]} accessible={false} importantForAccessibility="no-hide-descendants">
        <Botany kind={art} color={c.forestLine} sway={sway} />
      </View>
      {caption && (
        <Row gap={space.sm} style={{ flexWrap: 'wrap' }}>
          {captionLead}
          <T v="caption" color={c.onForest2}>{caption}</T>
          {captionExtra}
        </Row>
      )}
      {/* While the title fits in 2 lines it stays clear of the art (maxWidth 250);
          longer titles, or large text, run full width over the low-contrast art. */}
      <T
        v="hero"
        color={c.onForest}
        accessibilityRole="header"
        accessibilityLabel={titleLabel}
        style={{ marginTop: caption ? space.sm : 0, maxWidth: title.length <= 34 && !large && !wideTitle ? 250 : undefined }}
      >
        {title}
      </T>
      {meta && <T v="meta" color={c.onForest2} style={{ marginTop: 6 }}>{meta}</T>}
      {children}
      {action && (
        <Button
          kind="forest"
          label={action.label}
          onPress={action.onPress}
          accessibilityHint={action.hint}
          icon={action.icon}
          iconLeading
          style={{ marginTop: 18, alignSelf: 'flex-start' }}
        />
      )}
    </Card>
  );
}

// ── Section: headline + optional meta on the right ────────────────────
export function Section({ title, meta, style }: { title: string; meta?: string; style?: StyleProp<ViewStyle> }) {
  return (
    <View style={[styles.section, style]}>
      <T v="headline" accessibilityRole="header" style={{ flexShrink: 1 }}>{title}</T>
      {meta && <T v="meta">{meta}</T>}
    </View>
  );
}

// ── IconCircle: 40pt soft circle holding a row-size icon ──────────────
export function IconCircle({ children }: { children: ReactNode }) {
  const { c } = useTheme();
  return <View style={[styles.iconCircle, { backgroundColor: c.soft }]}>{children}</View>;
}

// ── ListRow: icon circle · title/subtitle · trailing · chevron, hairline below
export function ListRow({
  icon,
  lead,
  title,
  subtitle,
  trailing,
  onPress,
  last,
  chevron = true,
  dim,
  accessibilityLabel,
  accessibilityHint,
}: {
  icon?: ReactNode;
  /** A leading serif numeral block instead of an icon (e.g. "50 / questions"). */
  lead?: ReactNode;
  title: string;
  /** A string, or a node (e.g. a domain dot + text). */
  subtitle?: string | ReactNode;
  trailing?: ReactNode;
  /** Row text in `muted` (locked lessons). */
  dim?: boolean;
  onPress?: () => void;
  /** The last row in a list has no hairline. */
  last?: boolean;
  chevron?: boolean;
  accessibilityLabel?: string;
  accessibilityHint?: string;
}) {
  const { c } = useTheme();
  const body = (
    <>
      {icon && <IconCircle>{icon}</IconCircle>}
      {lead}
      <View style={{ flex: 1, minWidth: 0 }}>
        <T v="label" color={dim ? c.muted : undefined}>{title}</T>
        {typeof subtitle === 'string' ? <T v="meta" color={dim ? c.muted : undefined}>{subtitle}</T> : subtitle}
      </View>
      {trailing}
      {onPress && chevron && <ChevronRight size={18} color={c.muted} strokeWidth={ICON_STROKE} />}
      {/* Hairline inset to where the text starts. */}
      {!last && <View style={[styles.hairline, { left: icon ? 54 : 0, backgroundColor: c.line }]} />}
    </>
  );
  if (!onPress) return <View style={styles.listRow}>{body}</View>;
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel ?? (typeof subtitle === 'string' ? `${title}, ${subtitle}` : title)}
      accessibilityHint={accessibilityHint}
      onPress={onPress}
      style={({ pressed }) => [styles.listRow, pressed && { backgroundColor: c.soft }]}
    >
      {body}
    </Pressable>
  );
}

// ── ProgressBar: 0..1 ─────────────────────────────────────────────────
export function ProgressBar({ value, color, height = 8 }: { value: number; color?: string; height?: number }) {
  const { c } = useTheme();
  const pct = Math.max(0, Math.min(1, value)) * 100;
  const r = Math.min(height, radius.sm);
  return (
    <View
      accessibilityRole="progressbar"
      accessibilityValue={{ min: 0, max: 100, now: Math.round(pct) }}
      style={{ height, borderRadius: r, backgroundColor: c.track, overflow: 'hidden' }}
    >
      <View style={{ width: `${pct}%`, height, backgroundColor: color ?? c.accent, borderRadius: r }} />
    </View>
  );
}

// ── SegmentBar: quiz progress, one segment per question (spec §6) ─────
// Done = accent, current = ink2, rest = track. Over 20 questions it turns
// into one continuous bar so segments never get too thin to see.
export function SegmentBar({ total, done, current }: { total: number; done: number; current: number }) {
  const { c } = useTheme();
  const a11y = {
    accessibilityRole: 'progressbar' as const,
    accessibilityLabel: `Question ${current + 1} of ${total}`,
    accessibilityValue: { min: 0, max: total, now: done },
  };
  if (total > 20) {
    return (
      <View {...a11y} style={[styles.segTrack, { backgroundColor: c.track }]}>
        <View style={{ width: `${(done / total) * 100}%`, height: 4, backgroundColor: c.accent }} />
      </View>
    );
  }
  return (
    <View {...a11y} style={styles.segRow}>
      {Array.from({ length: total }, (_, i) => (
        <View
          key={i}
          style={[styles.seg, { backgroundColor: i < done ? c.accent : i === current ? c.ink2 : c.track }]}
        />
      ))}
    </View>
  );
}

// ── Domain dot: a small swatch in the domain's tone ───────────────────
// Domains 6+ (e.g. CISSP) reuse the 5 tones, drawn hollow so they stay distinct.
export function DomainDot({ domain }: { domain: DomainInfo }) {
  const { isDark } = useTheme();
  const color = domainColor(domain.tone, isDark);
  const hollow = Number(domain.id) > 5;
  return <View style={[styles.dot, hollow ? { borderWidth: 2, borderColor: color } : { backgroundColor: color }]} />;
}

// ── Tag: non-interactive label, no fill ("● IS Audit · Analysis") ─────
export function Tag({ label, domain, color }: { label: string; domain?: DomainInfo; color?: string }) {
  return (
    <View style={styles.tag}>
      {domain && <DomainDot domain={domain} />}
      <T v="meta" color={color} style={{ flexShrink: 1 }}>{label}</T>
    </View>
  );
}

// ── Chip: selectable filter (spec §6) ─────────────────────────────────
// Selected = ink fill + bg label + leading ✓ (shape AND colour, never green).
export function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) {
  const { c } = useTheme();
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ selected }}
      accessibilityLabel={label} // the ✓ is visual; "selected" state is spoken
      onPress={onPress}
      hitSlop={4} // 40pt chip + 4pt each side = 48pt touch target
      style={({ pressed }) => [
        styles.chip,
        {
          borderColor: selected ? c.ink : c.control,
          backgroundColor: selected ? c.ink : pressed ? c.soft : 'transparent',
        },
      ]}
    >
      {selected && <Check size={14} color={c.bg} strokeWidth={2.5} />}
      <Text maxFontSizeMultiplier={2} style={[styles.chipLabel, { color: selected ? c.bg : c.ink }]}>{label}</Text>
    </Pressable>
  );
}

// ── Toggle: an on/off switch in our colours ──────────────────────────
// Wraps the platform Switch so its thumb never falls back to a stock
// teal/blue. On the web build the "on" thumb needs `activeThumbColor`.
export function Toggle({
  value,
  onValueChange,
  disabled,
  accessibilityLabel,
}: {
  value: boolean;
  onValueChange: (v: boolean) => void;
  disabled?: boolean;
  accessibilityLabel: string;
}) {
  const { c } = useTheme();
  const webOnly = Platform.OS === 'web' ? ({ activeThumbColor: c.onBtn } as object) : {};
  return (
    <Switch
      accessibilityLabel={accessibilityLabel}
      value={value}
      disabled={disabled}
      onValueChange={onValueChange}
      thumbColor={c.onBtn}
      trackColor={{ true: c.btn, false: c.muted }}
      ios_backgroundColor={c.muted}
      {...webOnly}
    />
  );
}

// ── Stat tile: no box. Serif number + meta label, stacked ─────────────
export function Stat({ value, label, color, pct }: { value: string; label: string; color?: string; pct?: boolean }) {
  return (
    <View accessible accessibilityLabel={`${value}${pct ? ' percent' : ''} ${label}`}>
      <BigNum value={value} pct={pct} size={34} color={color} />
      <T v="meta" style={{ marginTop: space.xs, textAlign: 'center' }}>{label}</T>
    </View>
  );
}

// ── Tab bar label: "Today", with a 4pt dot under the active tab ───────
// The dot means the active tab isn't shown by colour alone (spec §6).
export function TabLabel({ label, focused }: { label: string; focused: boolean }) {
  const { c } = useTheme();
  return (
    // The Large Content Viewer props live on the tab BUTTON ((tabs)/_layout.tsx).
    <View style={styles.tabLabel}>
      <T v="tab" color={focused ? c.ink : c.muted}>{label}</T>
      <View style={[styles.tabDot, { backgroundColor: focused ? c.accent : 'transparent' }]} />
    </View>
  );
}

export function Row({ children, gap = space.md, style }: { children: ReactNode; gap?: number; style?: StyleProp<ViewStyle> }) {
  return <View style={[{ flexDirection: 'row', alignItems: 'center', gap }, style]}>{children}</View>;
}

export function Gap({ h = space.lg }: { h?: number }) {
  return <View style={{ height: h }} />;
}

const styles = StyleSheet.create({
  screenPad: { paddingHorizontal: space.gutter, paddingTop: space.lg, paddingBottom: space.xxxl * 2 },
  num: { fontVariant: ['tabular-nums'] },
  bigNum: { flexDirection: 'row', alignItems: 'flex-start' },
  pushed: { flexDirection: 'row', alignItems: 'center', minHeight: 52, gap: space.sm },
  pushedIcon: { width: 44, minHeight: 44, justifyContent: 'center' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: space.sm, marginTop: 18 },
  teachTag: { minHeight: 32, paddingHorizontal: space.md, borderRadius: radius.pill, flexDirection: 'row', alignItems: 'center', gap: 7 },
  teachDot: { width: 6, height: 6, borderRadius: 3 },
  seg2: { borderRadius: 22, padding: 3, gap: 3 },
  segItem: { minHeight: 40, borderRadius: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: space.sm },
  chipScroll: { gap: space.sm, paddingVertical: 4, paddingRight: space.xxxl },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: space.sm, paddingVertical: 4 },
  chipFade: { position: 'absolute', right: 0, top: 0, bottom: 0 },
  numUnit: { marginTop: 1 },
  noTouch: { pointerEvents: 'none' },
  button: {
    minHeight: 56, // spec: 56 tall, a comfortable thumb target (WCAG 2.5.8)
    borderRadius: radius.pill,
    borderWidth: 1.5,
    paddingHorizontal: space.xl,
    flexDirection: 'row',
    gap: space.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonForest: {
    minHeight: 48,
    borderRadius: radius.pill,
    borderWidth: 0,
    paddingHorizontal: 22,
    flexDirection: 'row',
    gap: space.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonGhost: {
    minHeight: 44,
    borderWidth: 0,
    paddingHorizontal: space.sm,
    flexDirection: 'row',
    gap: space.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonLabel: { fontFamily: font.sans600, fontSize: 17, lineHeight: 22 },
  card: { borderRadius: radius.md, borderWidth: 1.5, padding: space.lg },
  forest: { borderRadius: radius.lg, padding: 22, overflow: 'hidden' },
  // Dark mode: 1px inner top highlight so the panel separates from `bg`.
  forestLift: { borderTopWidth: 1, borderTopColor: forestHighlight },
  heroArt: { position: 'absolute', right: -18, top: -14 },
  section: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: space.md,
    marginTop: 30,
    marginBottom: 2,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listRow: { flexDirection: 'row', alignItems: 'center', gap: 14, minHeight: 64, paddingVertical: 13 },
  hairline: { position: 'absolute', right: 0, bottom: 0, height: 1 },
  segRow: { flex: 1, flexDirection: 'row', gap: 3 },
  seg: { flex: 1, height: 4, borderRadius: 2 },
  segTrack: { flex: 1, height: 4, borderRadius: 2, overflow: 'hidden' },
  dot: { width: 8, height: 8, borderRadius: radius.pill },
  tag: { flexDirection: 'row', alignItems: 'center', gap: space.sm },
  chip: {
    minHeight: 40,
    borderRadius: radius.pill,
    borderWidth: 1.5,
    paddingHorizontal: space.lg,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipLabel: { fontFamily: font.sans600, fontSize: 15, lineHeight: 20 },
  tabLabel: { alignItems: 'center', gap: 1 },
  tabDot: { width: 4, height: 4, borderRadius: 2 },
});

/**
 * A row of stats with hairlines above, below and between (spec §11 "You").
 * Each stat is centred in its cell. At large text sizes the row becomes a
 * vertical, left-aligned list so numbers never squeeze.
 */
export function StatRow({ children, style }: { children: ReactNode[]; style?: StyleProp<ViewStyle> }) {
  const { c } = useTheme();
  const stacked = useFontScale() >= LARGE_TEXT;
  const items = children.filter(Boolean);
  return (
    <View style={[{ flexDirection: stacked ? 'column' : 'row', borderTopWidth: 1, borderBottomWidth: 1, borderColor: c.line }, style]}>
      {items.map((child, i) => (
        <View
          key={i}
          style={[
            { paddingTop: space.lg, paddingBottom: 14 },
            // Side by side, each stat sits centred in its cell; stacked, it reads as a left-aligned list.
            !stacked && { flex: 1, alignItems: 'center', paddingHorizontal: space.sm },
            i > 0 && (stacked ? { borderTopWidth: 1, borderTopColor: c.line } : { borderLeftWidth: 1, borderLeftColor: c.line }),
          ]}
        >
          {child}
        </View>
      ))}
    </View>
  );
}

// ── Serif numerals (spec §10.4) ───────────────────────────────────────
/**
 * A Fraunces numeral with an optional raised % ("70" + a small, lifted "%").
 * Sizes: 52 = readiness / results, 34 = stats, 17–30 inline.
 * Numbers cap at ×1.3 text size: a fixed shape holds them.
 */
export function BigNum({
  value,
  pct,
  size,
  color,
  accessibilityLabel,
}: {
  value: string;
  pct?: boolean;
  size: NumeralSize | 34 | 52;
  color?: string;
  accessibilityLabel?: string;
}) {
  const { c } = useTheme();
  const fg = color ?? c.ink;
  return (
    <View style={styles.bigNum} accessible={Boolean(accessibilityLabel)} accessibilityLabel={accessibilityLabel}>
      <Text maxFontSizeMultiplier={1.3} style={[serifNumeral(size), styles.num, { color: fg }]}>{value}</Text>
      {pct && <Text maxFontSizeMultiplier={1.3} style={[percentSup(size), { color: fg, marginLeft: 2 }]}>%</Text>}
    </View>
  );
}

/** Figtree 12/16 unit under or beside a serif numeral ("due", "questions"). */
export function Unit({ children, color }: { children: string; color?: string }) {
  const { c } = useTheme();
  return <Text maxFontSizeMultiplier={2} style={[numeralUnit, styles.numUnit, { color: color ?? c.ink2 }]}>{children}</Text>;
}

/** Right-aligned count in a list row: serif 22 numeral over a unit ("59 / due"). */
export function Trail({ value, unit, color }: { value: string; unit: string; color?: string }) {
  return (
    <View style={{ alignItems: 'flex-end' }}>
      <BigNum value={value} size={22} color={color} />
      <Unit>{unit}</Unit>
    </View>
  );
}

/** Lead numeral for mock rows: serif 26 over a unit ("50 / questions"). */
export function Lead({ value, unit }: { value: string; unit: string }) {
  return (
    <View style={{ minWidth: 52 }}>
      <BigNum value={value} size={26} />
      <Unit>{unit}</Unit>
    </View>
  );
}

// ── Motion: content fade-in (spec §8) ─────────────────────────────────
/**
 * Fade + 8pt rise, 240ms ease-out, staggered 40ms per group (max 4 groups).
 * Under Reduce Motion it simply appears.
 */
export function Enter({ i = 0, children, style }: { i?: number; children: ReactNode; style?: StyleProp<ViewStyle> }) {
  const p = useSharedValue(0);
  useEffect(() => {
    p.value = withDelay(
      Math.min(i, 3) * 40,
      withTiming(1, { duration: 240, easing: Easing.out(Easing.cubic), reduceMotion: ReduceMotion.System }),
    );
  }, [i, p]);
  const anim = useAnimatedStyle(() => ({ opacity: p.value, transform: [{ translateY: (1 - p.value) * 8 }] }));
  return <Animated.View style={[anim, style]}>{children}</Animated.View>;
}

/** The phone's text-size multiplier (1 = default, 2 = 200%). */
export function useFontScale(): number {
  return useWindowDimensions().fontScale;
}

// ── Pushed-screen header (spec §6 "Header") ───────────────────────────
// 52pt bar: a 44pt back (‹) or close (X) button, a centred title, a right slot.
export function PushedHeader({
  title,
  onBack,
  icon = 'back',
  right,
  center,
}: {
  title?: string;
  onBack: () => void;
  icon?: 'back' | 'close';
  right?: ReactNode;
  /** Replaces the title (e.g. a progress bar). */
  center?: ReactNode;
}) {
  const { c } = useTheme();
  const Icon = icon === 'back' ? ChevronLeft : X;
  return (
    <View style={styles.pushed}>
      <Pressable
        accessibilityRole="button"
        accessibilityLabel={icon === 'back' ? 'Back' : 'Close'}
        onPress={onBack}
        hitSlop={4}
        style={[styles.pushedIcon, { marginLeft: -10, alignItems: 'center' }]}
      >
        <Icon size={ICON_SIZE.bar} color={c.ink} strokeWidth={ICON_STROKE} />
      </Pressable>
      {/* A custom centre (progress bar) stretches; a title is centred. */}
      <View style={{ flex: 1, alignItems: center ? 'stretch' : 'center' }}>
        {center ?? (title ? <T v="label" accessibilityRole="header" numberOfLines={1}>{title}</T> : null)}
      </View>
      <View style={[styles.pushedIcon, { marginRight: -10, alignItems: 'center' }]}>{right}</View>
    </View>
  );
}

// ── Empty state: a seedling, not a sad face (spec §11 "Empty state") ──
export function EmptyState({
  title,
  body,
  tags,
  compact,
}: {
  title: string;
  body: string;
  /** Teaching tags: the trap types that will appear here. */
  tags?: string[];
  /** Smaller seedling, for an empty list inside a busier screen. */
  compact?: boolean;
}) {
  const { c } = useTheme();
  return (
    <View style={{ alignItems: 'center', marginTop: compact ? space.sm : 46 }}>
      <View accessible={false} importantForAccessibility="no-hide-descendants">
        <Seedling color={c.accent} size={compact ? 96 : 170} />
      </View>
      <T v={compact ? 'headline' : 'hero'} center accessibilityRole="header" style={{ marginTop: compact ? space.xs : 22 }}>{title}</T>
      <T v={compact ? 'meta' : 'body'} color={c.ink2} center style={{ marginTop: space.sm, marginHorizontal: space.md }}>{body}</T>
      {tags && tags.length > 0 && (
        <View style={styles.tagRow}>
          {tags.map((t) => (
            <View key={t} style={[styles.teachTag, { backgroundColor: c.soft }]}>
              <View style={[styles.teachDot, { backgroundColor: c.clay }]} />
              <T v="meta">{t}</T>
            </View>
          ))}
        </View>
      )}
    </View>
  );
}

// ── Segmented control (spec §11 "Practice") ───────────────────────────
// `soft` track, the selected segment `raised` (+ soft shadow in light mode).
// Numeral options show a Fraunces 20 numeral + a small unit. Stacks into a
// column at large text sizes instead of squeezing.
/** Dark-mode fill for the selected segment (DESIGN_SYSTEM.md, Practice screen). */
const SEG_ON_DARK = '#2C372F';

export function Segmented<V extends string | number>({
  options,
  value,
  onChange,
  accessibilityLabel,
}: {
  options: { value: V; label: string; numeral?: string; icon?: (color: string) => ReactNode; spoken?: string }[];
  value: V;
  onChange: (v: V) => void;
  accessibilityLabel: string;
}) {
  const { c, isDark } = useTheme();
  const stacked = useFontScale() >= LARGE_TEXT;
  return (
    <View accessibilityRole="radiogroup" accessibilityLabel={accessibilityLabel} style={[styles.seg2, { backgroundColor: c.soft, flexDirection: stacked ? 'column' : 'row' }]}>
      {options.map((o) => {
        const on = o.value === value;
        return (
          <Pressable
            key={String(o.value)}
            accessibilityRole="radio"
            accessibilityState={{ checked: on }}
            accessibilityLabel={o.spoken ?? (o.numeral ? `${o.numeral} ${o.label}` : o.label)}
            onPress={() => onChange(o.value)}
            style={[
              styles.segItem,
              !stacked && { flex: 1 },
              // Selected = ink (spec §5): a 1.5px ink outline makes the choice
              // clear in both modes (fill alone was ~1.1:1, failing WCAG 1.4.11).
              // Fill: `raised` + shadow in light, the spec's lifted #2C372F in dark.
              // Unselected keeps a transparent border of the same width so nothing jumps.
              on
                ? { backgroundColor: isDark ? SEG_ON_DARK : c.raised, borderWidth: 1.5, borderColor: c.ink }
                : { borderWidth: 1.5, borderColor: 'transparent' },
              on && !isDark && raisedShadow,
            ]}
          >
            {o.icon?.(on ? c.ink : c.ink2)}
            {o.numeral ? (
              <>
                <BigNum value={o.numeral} size={20} />
                <Unit color={on ? c.ink : c.ink2}>{o.label}</Unit>
              </>
            ) : (
              <T v="caption" color={on ? c.ink : c.ink2}>{o.label}</T>
            )}
          </Pressable>
        );
      })}
    </View>
  );
}

// ── ChipRow: one scrolling line of chips with a fade at the right edge ─
// At large text sizes the chips wrap instead of scrolling (spec §10.7).
export function ChipRow({ children }: { children: ReactNode }) {
  const { c } = useTheme();
  const wrap = useFontScale() >= LARGE_TEXT;
  if (wrap) return <View style={styles.chipWrap}>{children}</View>;
  return (
    <View style={{ marginRight: -space.gutter }}>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chipScroll}>
        {children}
      </ScrollView>
      {/* Right-edge fade hints that the row scrolls. */}
      <Svg width={56} height="100%" style={[styles.chipFade, styles.noTouch]}>
        <Defs>
          <LinearGradient id="chipFade" x1="0" y1="0" x2="1" y2="0">
            <Stop offset="0" stopColor={c.bg} stopOpacity={0} />
            <Stop offset="1" stopColor={c.bg} stopOpacity={1} />
          </LinearGradient>
        </Defs>
        <Rect x="0" y="0" width="56" height="100%" fill="url(#chipFade)" />
      </Svg>
    </View>
  );
}

// ── Toggle row: a list row with a switch on the right ─────────────────
export function ToggleRow({
  title,
  subtitle,
  value,
  onValueChange,
  disabled,
  last,
}: {
  title: string;
  subtitle?: string;
  value: boolean;
  onValueChange: (v: boolean) => void;
  disabled?: boolean;
  last?: boolean;
}) {
  return (
    <ListRow
      title={title}
      subtitle={subtitle}
      last={last}
      trailing={<Toggle accessibilityLabel={title} value={value} disabled={disabled} onValueChange={onValueChange} />}
    />
  );
}
