#!/usr/bin/env python3
"""Regenerate data/originals/_bank_index.md from data/originals/d{1..5}.json.

The bank index is a compact reference for the cisa-exam-reviewer subagent
to perform cross-bank distinctness checks without reading the full per-domain
JSONs. Each entry: ID, domain, subtopic, framework_ref (first cite), and the
top 120 chars of key_concept.

Run after every batch authored. Should be wired as a pre-commit hook eventually.
"""
import json
import sys
from pathlib import Path

ROOT = Path("data/originals")
OUT = ROOT / "_bank_index.md"
DOMAINS = [1, 2, 3, 4, 5]


def first_citation(framework_ref: str) -> str:
    """Take the first citation from a semicolon-separated framework_ref string."""
    if not framework_ref:
        return ""
    return framework_ref.split(";")[0].strip()


def truncate(text: str, max_chars: int) -> str:
    if not text or len(text) <= max_chars:
        return text or ""
    return text[: max_chars - 1].rstrip() + "…"


def render_question(q: dict) -> str:
    qid = q["id"]
    subtopic = q["subtopic"]
    diff = q["difficulty"][0].upper()  # F / A / N
    cite = truncate(first_citation(q.get("framework_ref", "")), 60)
    concept = truncate(q.get("key_concept", ""), 120)
    return f"- `{qid}` [{diff}] **{subtopic}** | {cite} | {concept}"


def main() -> int:
    lines: list[str] = []
    lines.append("# CISA Question Bank Index")
    lines.append("")
    lines.append(
        "Compact reference for cross-bank distinctness checking. "
        "Auto-generated by `scripts/regenerate_bank_index.py`. "
        "Format per question: `id [tier] subtopic | framework_ref | key_concept (truncated)`. "
        "Tier: F=foundational, A=application, N=analysis."
    )
    lines.append("")

    total = 0
    for d in DOMAINS:
        path = ROOT / f"d{d}.json"
        if not path.exists():
            continue
        data = json.loads(path.read_text())
        questions = data.get("questions", [])
        if not questions:
            continue

        lines.append(f"## Domain {d}: {data.get('domain_name', '')} ({len(questions)} questions)")
        lines.append("")
        for q in questions:
            lines.append(render_question(q))
        lines.append("")
        total += len(questions)

    lines.append(f"---")
    lines.append(f"")
    lines.append(f"**Total bank size:** {total} questions across {len([d for d in DOMAINS if (ROOT / f'd{d}.json').exists()])} domains.")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} with {total} questions indexed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
